### ISSUE TITLE
SSR always show loading with typescript

### ISSUE THREAD

**Issue by Aaike** [faceyspacey/universal-demo#22]
Hi , 

I am trying to use universal-react-component with my app - which is written in typescript
To make it work, I had to convert the "main" file where the universal component is created to a normal js  file and then things work fine... with a .tsx extension the SSR only shows Loading...

To demonstrate the issue i forked this demo repo here : https://github.com/Aaike/universal-demo
If you test the master branch there you will see things work just fine.
In the master branch i converted all files to typescript except the App.js

If you then checkout the `typescript` branch and test again, there are some issues...
The server side rendering keeps showing the universal component in it's loading state.
if you check the page source it only has "Loading..." where the component is supposed to be.
The only difference in this branch is that I've renamed App.js to App.tsx...

note: there also seems to be an issue with the css when changing App.js to App.tsx - but im not worried about that in particular for this demo.

I can't figure out why the SSR is not working with only that small change, so any help would be greatly appreciated.

**Comment by faceyspacey** [comment]
For typescript you have to copy what `babel-plugin-universal-import` does:

https://github.com/faceyspacey/babel-plugin-universal-import#what-it-does

if your server is bundled by webpack, you can omit the `path` option.

You may also be able to omit the inner call to `universalImport` and put all these options on the second `options` argument to `universal`, but if that doesn't work, just keep it.

**Comment by faceyspacey** [comment]
Also I just made an update that should make it easier for typescript users. Upgrade your package, and you leave out the nested universalImport call.

So before you might have had this:

import universal from 'react-universal-component'
import universalImport from 'babel-plugin-universal-import/universalImport.js'
import importCss from 'babel-plugin-universal-import/importCss.js'

const UniversalComponent = universal(props => universalImport({
  chunkName: props => props.page,
  resolve: props => require.resolveWeak(`./${props.page}`),
  load: props => Promise.all([
    import( /* webpackChunkName: '[request]' */ `./${props.page}`),
    importCss(page)
  ]).then(proms => proms[0])
}));

Now you can have this:

```
import universal from 'react-universal-component'
import importCss from 'babel-plugin-universal-import/importCss.js'

const load = props => Promise.all([
    import( /* webpackChunkName: '[request]' */ `./${props.page}`),
    importCss(page)
  ]).then(proms => proms[0])

const UniversalComponent = universal(load, {
  chunkName: props => props.page,
  resolve: props => require.resolveWeak(`./${props.page}`)
});
```
> notice `chunkName` and `resolve` as standard options on the 2nd options argument.

**Comment by faceyspacey** [comment]
https://github.com/faceyspacey/babel-plugin-universal-import#typescript-and-non-babel-environments

**Comment by jkomyno** [comment]
@Aaike would you please be able to post a diff gist or an example repo on how to properly set up react-universal-component with TypeScript 2+?
