### ISSUE TITLE
Two requests for each CSS file on client navigation

### ISSUE THREAD

**Issue by corydeppen** [faceyspacey/universal-demo#23]
This isn't meant to be critical, but I wanted to preface this issue by mentioning it's tough to know where to submit an issue given the variety of repositories for the different pieces of the universal tool set. I'm submitting this here because I ran into it while running this app from master, but I'd be happy to submit it in a more appropriate repo if necessary.

I've noticed there are two requests for each CSS file following the initial server render. Following each client route change, the CSS file has `stylesheet` and `text/css` request. This looks odd and I can't imagine it's intended, but I'm unclear where the issue lies.

![2017-12-31_17-26-21](https://user-images.githubusercontent.com/313264/34464510-cbb44b08-ee4f-11e7-881c-6ce1fedc9367.png)

**Comment by corydeppen** [comment]
Looks like faceyspacey/babel-plugin-universal-import#26 mentions this issue and references a PR to address it.

**Comment by faceyspacey** [comment]
The PR was just merged. That should solve it for all browsers that don't have the related `onload` callback issues.
