### ISSUE TITLE
Trying to upgrade to Babel7 (and TypeScript)

### ISSUE THREAD

**Issue by Industrial** [faceyspacey/universal-demo#25]
Hi.

I have forked your project at https://github.com/Industrial/universal-demo and I am trying to get it to use Babel7 so that I can use TypeScript easily. I have it *almost* working, however I am getting an error `Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op.` which happens at https://github.com/Industrial/universal-demo/blob/master/src/components/App.tsx#L41 .

At first I thought it was the HMR so I added the unlisten part and moved it to `componentDidMount` and `componentWillUnmount` but I'm still getting the same error.

To reproduce:
```
git clone https://github.com/Industrial/universal-demo.git;
cd universal-demo;
npm i;
npm run development;
```
Click the button to pop the warning.

Sorry to drag you into my project like this, but I've googled and asked for help in different communities/channels and couldn't find a solution.

**Comment by faceyspacey** [comment]
Hey there, some point soon I'm going to be able to focus on babel 7 support, but I won't be able to just yet.
