### ISSUE TITLE
Webpack 4

### ISSUE THREAD

**Issue by MartinCerny-awin** [faceyspacey/universal-demo#27]
There were major changes to code splitting in webpack 4 and the `CommonsChunkPlugin` got deprecated. I have tried to upgrade my project into webpack 4, but I didn't manage to figure out how to use `SplitChunksPlugin` with `react-universal-component`.

**Comment by primozs** [comment]
Same here.

**Comment by faceyspacey** [comment]
Here's how it's done in WP 4:

https://github.com/faceyspacey/react-universal-component/issues/113#issuecomment-378969107

**Comment by zackljackson** [comment]
@MartinCerny-awin @primozs Ill be Submitting a PR soon with updated readme's and some code updates. The comment should be enough In the meantime

**Comment by primozs** [comment]
@zackljackson thx!

**Comment by zackljackson** [comment]
https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/issues/60#issuecomment-392317314
