### ISSUE TITLE
Output file name hashing seems to be broken

### ISSUE THREAD

**Issue by alexstanbury** [faceyspacey/universal-demo#31]
Asked this in Reactlandia chat but it's a bit dead over there at the moment so thought I'd try here...

I'm testing this demo and I'm having a hard time understanding what's going on with hash names of the files. Not sure whether I'm not understanding what's meant to happen though.

Couple of questions:
1) Should the main.js file name hash change if I simply change a css property in one of the .styl files? For example, if I change a background colour from blue to orange, then rebuild the files using npm run start:prod, the hash of the main.js changes meaning caching for this file won't work. Why does the hash of this file change even though its contents surely haven't?
2) Should the generated .css files have a hash in their file name too? Is there any reason this is not set by default in the demo?

I've just tested the same with RFR Demo and it behaves as expected, changing value in a .css file only updates the hash of that .css file, nothing else.

From further testing I can see that the compiled main.js has references to the file names of all the chunks, which I guess is causing this issue.

```/******/     // script path function
/******/     function jsonpScriptSrc(chunkId) {
/******/         return __webpack_require__.p + "" + ({"components-Bar":"components-Bar","components-Baz":"components-Baz","components-Example":"components-Example","components-FaceySpacey":"components-FaceySpacey","components-Foo":"components-Foo","components-ReduxFirstRouter":"components-ReduxFirstRouter","components-Rudy":"components-Rudy","components-Universal":"components-Universal","css-Bar":"css-Bar","css-Baz":"css-Baz","css-Example":"css-Example","css-FaceySpacey":"css-FaceySpacey","css-Foo":"css-Foo","css-ReduxFirstRouter":"css-ReduxFirstRouter","css-Rudy":"css-Rudy","css-Universal":"css-Universal","css-mixins":"css-mixins"}[chunkId]||chunkId) + "." + {"components-Bar":"d6e05c80ee9e04616714","components-Baz":"f5126f1b8fbe30f43214","components-Example":"19d907ab3a9d69bd4b98","components-FaceySpacey":"a07960cb130247111e59","components-Foo":"e0b0eadcf1b5069a6c48","components-ReduxFirstRouter":"6fac86004d342946a7f3","components-Rudy":"67bf52fd3a78b96bc315","components-Universal":"4b7cbd66beb5c903cc1c","css-Bar":"792518d52cb8898c671c","css-Baz":"618edf0ab77f96e23c7c","css-Example":"306b2c440ad5b0b0e3a4","css-FaceySpacey":"db84f6ad93795feba111","css-Foo":"cc1143f4cee0e9f6b135","css-ReduxFirstRouter":"7c6ce0f3b0d059ba0904","css-Rudy":"dbdae9ce0e6e62e979d2","css-Universal":"1822a7757a4c4eecb2c3","css-mixins":"550fc201bf5f1d6c8f42"}[chunkId] + ".js"
/******/     }
```

**Comment by ScriptedAlchemy** [comment]
It depends on the build setup, if we use css in js - along with not so great code splitting - it can just dump it back in main.js

Can you diff the the build and see what changed?
