### ISSUE TITLE
[PR] TypeScript Support ❤️

### ISSUE THREAD

**Issue by Gorhom** [faceyspacey/universal-demo#35]
Hi @faceyspacey , 

thanks for this such a great library, it helps me a lot in my projects. I would love to contribute to the demo with `TypeScript Support` which I have done on my own forked repository:

[universal-demo-typescript](https://github.com/Gorhom/universal-demo-typescript)

Should i create a PR to master or wait for you to create a new branch for Typescript ?

hopefully you guys find it helpful 😇

**Comment by ScriptedAlchemy** [comment]
yes please!

We are trying to move our projects to TS. updated definitions will be great

**Comment by Gorhom** [comment]
Hi @ScriptedAlchemy ,

> We are trying to move our projects to TS

That's great ! I have created a PR to master for now, next step gonna be update ts definitions 👍
