### ISSUE TITLE
Loading CSS chunks before JS execution on client

### ISSUE THREAD

**Issue by believer-ufa** [faceyspacey/universal-demo#40]
Hello,

Thanks for the great example.

I found that css chunks are not added to HTML before JS execution (eg on the SSR).

I fun the following commands:

```
npx yarn
npx yarn start:prod
```

![image](https://user-images.githubusercontent.com/801727/50406608-94660880-07e9-11e9-8ad1-332d857b5eec.png)

If i disable JS in browser console, i see only one main CSS chunk `/static/main.css`.

And see next output in terminal:

```
[FLUSH CHUNKS]: Unable to find components/Foo in Webpack chunks. Please check usage of Babel plugin.
PATH /
DYNAMIC CHUNK NAMES RENDERED [ 'components/Foo' ]
SCRIPTS SERVED [ 'main.3899d8aaf5c32b55394b.js' ]
STYLESHEETS SERVED [ 'main.css' ]
```

If i enable JS - everything works fine. But.. you know. I thought that libraries allow to inject css chunks in html template before js execution on client.

Maybe its just a small error in current boilerplate code? Please help )

**Comment by ScriptedAlchemy** [comment]
The demo is just outdated.  Look for a project called Icarus under my repo. It’s built for enterprise and should do the job

**Comment by ScriptedAlchemy** [comment]
I’m pretty sure I just need to update the modules and it’ll work again haha.

**Comment by believer-ufa** [comment]
Tried to update, but it doesn't work. Maybe because it really have [unconfigured babel](https://github.com/faceyspacey/universal-demo/blob/master/.babelrc)?)

**Comment by believer-ufa** [comment]
I am slightly advanced in studying the problem.

I think problem in Webpack `assetsByChunkName` stats information.

If add `console.info({ assetsByChunkName: clientStats.assetsByChunkName });` in `render.tsx` we get next output:

```
[FLUSH CHUNKS]: Unable to find components/Foo in Webpack chunks. Please check usage of Babel plugin.
PATH /
DYNAMIC CHUNK NAMES RENDERED [ 'components/Foo' ]
{ assetsByChunkName:
   { main:
      [ 'frontend.main.build.a1ce84cb84895daafb2b.css',
        'main.ece86fdbd568956c52b6.js',
        'frontend.main.build.a1ce84cb84895daafb2b.css.map',
        'main.ece86fdbd568956c52b6.js.map' ] } }
SCRIPTS SERVED [ 'main.ece86fdbd568956c52b6.js' ]
STYLESHEETS SERVED [ 'frontend.main.build.a1ce84cb84895daafb2b.css' ]
```

Trying to properly configure webpack to get correct assetsByChunkName object with listing all project chunks.

------------

Your project Icarus really working correctly, thanks! It really helpful.

**Comment by believer-ufa** [comment]
I still dont know deep reasons why it work as work today, but to fix that problem slightly needs to change UniversalComponent logic in that project on [that lines](https://github.com/faceyspacey/universal-demo/blob/727a89a83ad191c29899ffcdf185f1caa05df773/src/client/UniversalComponent.tsx#L14-L24).

Is we change that code to next:

```
const UniversalComponent = universal(determineHowToLoad, {
  chunkName: props => props.page.replace('/','-'),
  // @ts-ignore
  // resolve: props => require.resolveWeak(`./${props.page}`),
  onError: error => {
    throw error
  },
  minDelay: 1200,
  loading: Loading,
  error: NotFound
})
```

Everything starts works as excepted.

Anyway, thanks for any help )

**Comment by ScriptedAlchemy** [comment]
So that rename chunk. You need to check Babel-Universal  and Universal docs. Also use the latest versions. You Reuther need to disable rename or enable it. One works for some not for others. Also the dashed name exists because it’s harder to resolve by slash. Easy solution is to just change the chunknames to only be hashes with no [name]

Also feel free to PR flush chunks. Of you can get it to resolve better than I’ll get rid of the dash crap and only use the natural convention

**Comment by ScriptedAlchemy** [comment]
Your last comment is because you are not using Babel Universal import plugin. Which builds the HOC for you

**Comment by ScriptedAlchemy** [comment]
Ur implementation is fine tho! We built it to work without Babel- just a pain the ass
