### ISSUE TITLE
Not updated dynamically classes in js files (HRM don't work)

### ISSUE THREAD

**Issue by 12evgen** [faceyspacey/universal-demo#44]
I started the demo.
I try to change the class for the button, but the class is updated only after reloading the page. In the console writes the following
![screenshot from 2019-02-28 17-12-15](https://user-images.githubusercontent.com/25562185/53562649-1ec94080-3b7c-11e9-92f7-5f9b2bab7f57.png)
Does anyone know the reason?

**Comment by nourel** [comment]
I created a PR that fixes this issue:
https://github.com/faceyspacey/universal-demo/pull/46

**Comment by ScriptedAlchemy** [comment]
fixed this in my plugin
