### ISSUE TITLE
Babel 7 migration

### ISSUE THREAD

**Issue by futurfutur** [faceyspacey/universal-demo#45]
Any plans on Babel 7 migration?
Trying to migrate by myself with following changes:
Package.json

  "dependencies": {
    "@babel/plugin-proposal-class-properties": "^7.4.0",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/preset-env": "^7.4.2",
    "colors": "^1.3.3",
    "express": "^4.16.4",
    "express-no-favicons": "^0.0.1",
    "extract-css-chunks-webpack-plugin": "^3.3.2",
    "history": "^4.7.2",
    "prop-types": "^15.6.2",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-universal-component": "^3.0.3",
    "webpack-dev-middleware": "^3.5.1",
    "webpack-flush-chunks": "^2.0.3"
  },
  "devDependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.4.0",
    "@babel/preset-react": "^7.0.0",
    "babel-eslint": "^10.0.1",
    "babel-loader": "^8.0.5",
    "babel-plugin-universal-import": "^4.0.0",
    "babel-watch": "^7.0.0",
    "commitizen": "^3.0.5",
    "cross-env": "^5.2.0",
    "css-loader": "^1.0.0",
    "cz-conventional-changelog": "^2.1.0",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-flowtype": "^2.50.3",
    "eslint-plugin-import": "^2.16.0",
    "eslint-plugin-jsx-a11y": "^6.2.0",
    "eslint-plugin-react": "^7.12.4",
    "husky": "^1.3.1",
    "lint-staged": "^4.2.3",
    "poststylus": "^1.0.0",
    "prettier": "^1.16.1",
    "react-hot-loader": "^4.6.3",
    "rimraf": "^2.6.3",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2",
    "travis-github-status": "^1.6.3",
    "webpack": "4.28.0",
    "webpack-hot-middleware": "^2.24.3",
    "webpack-hot-server-middleware": "^0.5.0",
    "write-file-webpack-plugin": "^4.5.0"
  },
  
`

.babelrc
`{

  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
    "universal-import"
  ],
  "env": {
    "development": {
      "plugins": [
        "@babel/plugin-proposal-class-properties",
        "react-hot-loader/babel"
      ]
    }
  }
}`

Got following error:
`ERROR in multi regenerator-runtime/runtime.js ./server/render.js
    Module not found: Error: Can't resolve 'regenerator-runtime/runtime.js' in 'C:\Code\DEMOS\rua3'
     @ multi regenerator-runtime/runtime.js ./server/render.js main[0]
i ｢wdm｣: Failed to compile.`

Any ideas?

**Comment by ScriptedAlchemy** [comment]
Done
