### ISSUE TITLE
ERR_INCOMPLETE_CHUNKED_ENCODING errors after 5 seconds

### ISSUE THREAD

**Issue by malixsys** [faceyspacey/universal-demo#7]
I always receive ERR_INCOMPLETE_CHUNKED_ENCODING after 5 seconds or so...

![image](https://user-images.githubusercontent.com/664650/28636020-cea8a7d0-720a-11e7-83a2-038309491b51.png)

**Comment by faceyspacey** [comment]
i was in the process of updating the demo. Can you check the readme and follow the new directions. It will require you using a PR that was just merged into webpack but not published. It's a big improvement for us. 

For more info, check the updated React Universal Component readme:

https://github.com/faceyspacey/react-universal-component
